name: dart_orm
version: 0.1.2-dev
description: >
  Easy-to-use and easy-to-setup database ORM for dart.
author: Ustimenko Sergey <ustims@gmail.com>
homepage: https://github.com/ustims/DartORM
dev_dependencies:
  test: '^0.12.0'
  dart_orm_adapter_postgresql: any
  dart_orm_adapter_mongodb: any
  dart_orm_adapter_mysql: any
